package:
  name: r-flock
  version: "0.7"
source:
  url: "{{ cran_mirror }}/src/contrib/flock_0.7.tar.gz"
  sha256: 47ebdeaeeb63ec93c800782bafa7f2846f73bb905adb6a3b5c44b248ce1de9fd
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - make
  host:
    - r-base
    - r-rcpp
  run:
    - r-base
    - r-rcpp
test:
  commands:
    - $R -e "library('flock')"
about:
  home: https://CRAN.R-project.org/package=flock
  license: Apache License 2.0
  summary: Implements synchronization between R processes (spawned by using the "parallel" package
    for instance) using file locks. Supports both exclusive and shared locking.
  license_family: APACHE
