package:
  name: r-rmio
  version: "0.4.0"
source:
  url: "{{ cran_mirror }}/src/contrib/rmio_0.4.0.tar.gz"
  sha256: 1ed6046ee36f34fca5357e0f18ab2f53b9d85032ec2cbcadb9f33a8fa7456dbe
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - r-base
    - r-bigassertr
    - r-ff
  run:
    - r-base
    - r-bigassertr
    - r-ff
test:
  commands:
    - $R -e "library('rmio')"
about:
  home: https://github.com/privefl/rmio
  license: GPL-3
  summary: Provides header files of 'mio', a cross-platform C++11 header-only library for memory
    mapped file IO <https://github.com/mandreyel/mio>.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
