package:
  name: r-base64url
  version: "1.4"
source:
  url: "{{ cran_mirror }}/src/contrib/base64url_1.4.tar.gz"
  sha256: 1d058f138660e9155ebb331d7a2561e2541ee3321b8da90f6c41fd8dcc122c58
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - "{{ compiler('c') }}"
    - make
  host:
    - r-base
    - r-backports
  run:
    - r-base
    - r-backports
test:
  commands:
    - $R -e "library('base64url')"           # [not win]
about:
  home: https://github.com/mllg/base64url
  license: GPL-3
  summary: In contrast to RFC3548, the 62nd character ("+") is replaced with "-", the 63rd character
    ("/") is replaced with "_". Furthermore, the encoder does not fill the string with
    trailing "=". The resulting encoded strings comply to the regular expression pattern
    "[A-Za-z0-9_-]" and thus are safe to use in URLs or for file names. The package
    also comes with a simple base32 encoder/decoder suited for case insensitive file
    systems.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
